[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "twine"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = 6.0
addopts = "-ra -q"
log_cli = 1
log_cli_level = "INFO"
testpaths = [ "tests" ]